// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated on: 2025-10-23T05:40:09.492Z
// This file is automatically generated by generate-docs-config.js

export const docsStructure = [
  {
    "id": "01-foundational-machine-learning",
    "title": "01 Foundational Machine Learning",
    "path": "/01_Foundational_Machine_Learning/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "01-foundational-machine-learning-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-01-linear-algebra-md",
            "title": "Linear Algebra for Machine Learning",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/01_Linear_Algebra.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-01-machine-learning-foundations-2024-2025-md",
            "title": "Machine Learning Foundations: 2024-2025 Edition",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/01_Machine_Learning_Foundations_2024_2025.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-02-calculus-and-optimization-md",
            "title": "Calculus and Optimization for Machine Learning",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/02_Calculus_and_Optimization.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-02-supervised-learning-2024-2025-md",
            "title": "Supervised Learning: 2024-2025 Edition",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/02_Supervised_Learning_2024_2025.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-03-probability-theory-md",
            "title": "Probability Theory for Machine Learning",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/03_Probability_Theory.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-03-unsupervised-learning-2024-2025-md",
            "title": "Unsupervised Learning: 2024-2025 Edition",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/03_Unsupervised_Learning_2024_2025.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-04-information-theory-md",
            "title": "Information Theory for Machine Learning",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/04_Information_Theory.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-01-theory-foundations-05-numerical-methods-md",
            "title": "Numerical Methods in Machine Learning",
            "path": "/01_Foundational_Machine_Learning/01_Theory_Foundations/05_Numerical_Methods.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "01-foundational-machine-learning-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/01_Foundational_Machine_Learning/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "01-foundational-machine-learning-02-practical-implementations-01-linear-algebra-applications-md",
            "title": "Linear Algebra Applications in Machine Learning",
            "path": "/01_Foundational_Machine_Learning/02_Practical_Implementations/01_Linear_Algebra_Applications.md",
            "isDirectory": false
          },
          {
            "id": "01-foundational-machine-learning-02-practical-implementations-02-numerical-methods-applications-md",
            "title": "Numerical Methods Applications in Machine Learning",
            "path": "/01_Foundational_Machine_Learning/02_Practical_Implementations/02_Numerical_Methods_Applications.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "01-main-guides",
    "title": "01 Main Guides",
    "path": "/01_Main_Guides",
    "isDirectory": true,
    "children": [
      {
        "id": "01-main-guides-01-ai-comprehensive-guide",
        "title": "01 AI Comprehensive Guide",
        "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/README.md",
        "isDirectory": true,
        "children": [
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-01-introduction-to-ai-md",
            "title": "Chapter 1: Introduction to Artificial Intelligence",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/01_Introduction_to_AI.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-02-philosophical-origins-md",
            "title": "Chapter 2: The Philosophical Origins",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/02_Philosophical_Origins.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-03-birth-of-ai-md",
            "title": "Chapter 3: The Birth of AI (1940s-1950s)",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/03_Birth_of_AI.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-04-early-ai-approaches-md",
            "title": "Chapter 4: Early AI Approaches (1950s-1970s)",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/04_Early_AI_Approaches.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-05-mathematical-foundations-md",
            "title": "Chapter 5: Mathematical Foundations",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/05_Mathematical_Foundations.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-06-computational-theory-md",
            "title": "Chapter 6: Computational Theory",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/06_Computational_Theory.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-readme-md",
            "title": "The Ultimate Guide to Artificial Intelligence: From Scratch to Latest Technologies",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/README.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "01-main-guides-00-readme-md",
        "title": "Main Guides",
        "path": "/01_Main_Guides/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "01-main-guides-01-ai-comprehensive-guide-md",
        "title": "The Ultimate Guide to Artificial Intelligence: From Scratch to Latest Technologies",
        "path": "/01_Main_Guides/01_AI_Comprehensive_Guide.md",
        "isDirectory": false
      },
      {
        "id": "01-main-guides-02-ai-comprehensive-guide-plan-md",
        "title": "AI Comprehensive Guide: From Scratch to Latest Technologies",
        "path": "/01_Main_Guides/02_AI_Comprehensive_Guide_Plan.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "02-advanced-deep-learning",
    "title": "02 Advanced Deep Learning",
    "path": "/02_Advanced_Deep_Learning/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "02-advanced-deep-learning-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/02_Advanced_Deep_Learning/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "02-advanced-deep-learning-01-theory-foundations-01-neural-network-basics-md",
            "title": "1. Neural Network Fundamentals",
            "path": "/02_Advanced_Deep_Learning/01_Theory_Foundations/01_Neural_Network_Basics.md",
            "isDirectory": false
          },
          {
            "id": "02-advanced-deep-learning-01-theory-foundations-02-convolutional-neural-networks-md",
            "title": "2. Convolutional Neural Networks (CNNs)",
            "path": "/02_Advanced_Deep_Learning/01_Theory_Foundations/02_Convolutional_Neural_Networks.md",
            "isDirectory": false
          },
          {
            "id": "02-advanced-deep-learning-01-theory-foundations-03-recurrent-neural-networks-md",
            "title": "3. Recurrent Neural Networks and Sequential Processing",
            "path": "/02_Advanced_Deep_Learning/01_Theory_Foundations/03_Recurrent_Neural_Networks.md",
            "isDirectory": false
          },
          {
            "id": "02-advanced-deep-learning-01-theory-foundations-04-transformers-and-attention-md",
            "title": "4. Transformers and Attention Mechanisms",
            "path": "/02_Advanced_Deep_Learning/01_Theory_Foundations/04_Transformers_and_Attention.md",
            "isDirectory": false
          },
          {
            "id": "02-advanced-deep-learning-01-theory-foundations-05-graph-neural-networks-md",
            "title": "5. Graph Neural Networks",
            "path": "/02_Advanced_Deep_Learning/01_Theory_Foundations/05_Graph_Neural_Networks.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "02-advanced-deep-learning-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/02_Advanced_Deep_Learning/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "02-advanced-deep-learning-02-practical-implementations-01-pytorch-implementations-md",
            "title": "PyTorch Implementations of Advanced Deep Learning Architectures",
            "path": "/02_Advanced_Deep_Learning/02_Practical_Implementations/01_PyTorch_Implementations.md",
            "isDirectory": false
          },
          {
            "id": "02-advanced-deep-learning-02-practical-implementations-02-tensorflow-implementations-md",
            "title": "TensorFlow Implementations of Advanced Deep Learning Architectures",
            "path": "/02_Advanced_Deep_Learning/02_Practical_Implementations/02_TensorFlow_Implementations.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "02-advanced-deep-learning-03-case-studies",
        "title": "03 Case Studies",
        "path": "/02_Advanced_Deep_Learning/03_Case_Studies",
        "isDirectory": true,
        "children": [
          {
            "id": "02-advanced-deep-learning-03-case-studies-01-computer-vision-applications-md",
            "title": "Computer Vision Applications: Case Studies",
            "path": "/02_Advanced_Deep_Learning/03_Case_Studies/01_Computer_Vision_Applications.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "02-advanced-deep-learning-00-overview-enhanced-md",
        "title": "Section II: Advanced Deep Learning Architectures - Enhanced Overview",
        "path": "/02_Advanced_Deep_Learning/00_Overview_Enhanced.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "02-industry-examples",
    "title": "02 Industry Examples",
    "path": "/02_Industry_Examples",
    "isDirectory": true,
    "children": [
      {
        "id": "02-industry-examples-02-healthcare-ai-examples",
        "title": "02 Healthcare AI Examples",
        "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/README.md",
        "isDirectory": true,
        "children": [
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-00-healthcare-ai-examples-index-md",
            "title": "Healthcare AI Examples: Modular Documentation",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/00_Healthcare_AI_Examples_Index.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-01-medical-imaging-and-diagnostics-md",
            "title": "Medical Imaging and Diagnostics AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/01_Medical_Imaging_and_Diagnostics.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-02-electronic-health-records-md",
            "title": "Electronic Health Records (EHR) Management AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/02_Electronic_Health_Records.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-03-drug-discovery-and-development-md",
            "title": "Drug Discovery and Development AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/03_Drug_Discovery_and_Development.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-04-clinical-decision-support-md",
            "title": "Clinical Decision Support Systems AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/04_Clinical_Decision_Support.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-05-implementation-and-integration-md",
            "title": "Implementation and Integration Strategies",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/05_Implementation_and_Integration.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-readme-md",
            "title": "Healthcare AI Examples - Modular Documentation",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/README.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "02-industry-examples-00-industry-examples-index-md",
        "title": "AI Examples Master Index",
        "path": "/02_Industry_Examples/00_Industry_Examples_Index.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-00-readme-md",
        "title": "Industry Examples",
        "path": "/02_Industry_Examples/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-01-finance-ai-examples-md",
        "title": "AI in Finance: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/01_Finance_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-02-healthcare-ai-examples-md",
        "title": "AI Examples in Healthcare: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/02_Healthcare_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-03-manufacturing-ai-examples-md",
        "title": "AI Examples in Manufacturing: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/03_Manufacturing_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-04-ecommerce-ai-examples-md",
        "title": "AI Examples in E-commerce: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/04_Ecommerce_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-05-agriculture-ai-examples-md",
        "title": "AI Examples in Agriculture: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/05_Agriculture_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-06-education-ai-examples-md",
        "title": "AI in Education: Comprehensive Implementation Examples",
        "path": "/02_Industry_Examples/06_Education_AI_Examples.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "03-natural-language-processing",
    "title": "03 Natural Language Processing",
    "path": "/03_Natural_Language_Processing/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "03-natural-language-processing-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/03_Natural_Language_Processing/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "03-natural-language-processing-01-theory-foundations-01-linguistic-foundations-md",
            "title": "Linguistic Foundations for NLP",
            "path": "/03_Natural_Language_Processing/01_Theory_Foundations/01_Linguistic_Foundations.md",
            "isDirectory": false
          },
          {
            "id": "03-natural-language-processing-01-theory-foundations-02-transformer-architecture-theory-md",
            "title": "Transformer Architecture Theory: Mathematical Foundations",
            "path": "/03_Natural_Language_Processing/01_Theory_Foundations/02_Transformer_Architecture_Theory.md",
            "isDirectory": false
          },
          {
            "id": "03-natural-language-processing-01-theory-foundations-03-large-language-models-theory-md",
            "title": "Large Language Models Theory: Mathematical Foundations and Scaling Laws",
            "path": "/03_Natural_Language_Processing/01_Theory_Foundations/03_Large_Language_Models_Theory.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "03-natural-language-processing-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/03_Natural_Language_Processing/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "03-natural-language-processing-02-practical-implementations-01-core-nlp-techniques-md",
            "title": "Core NLP Techniques: Practical Implementations",
            "path": "/03_Natural_Language_Processing/02_Practical_Implementations/01_Core_NLP_Techniques.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "03-terminology-references",
    "title": "03 Terminology References",
    "path": "/03_Terminology_References",
    "isDirectory": true,
    "children": [
      {
        "id": "03-terminology-references-00-readme-md",
        "title": "Terminology References",
        "path": "/03_Terminology_References/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "03-terminology-references-01-ai-comprehensive-terminology-md",
        "title": "AI/ML/DL Comprehensive Terminology Master Reference",
        "path": "/03_Terminology_References/01_AI_Comprehensive_Terminology.md",
        "isDirectory": false
      },
      {
        "id": "03-terminology-references-02-ml-dl-comprehensive-terminology-md",
        "title": "Comprehensive AI/ML/DL Terminology Guide",
        "path": "/03_Terminology_References/02_ML_DL_Comprehensive_Terminology.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "04-computer-vision",
    "title": "04 Computer Vision",
    "path": "/04_Computer_Vision/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "04-computer-vision-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/04_Computer_Vision/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "04-computer-vision-01-theory-foundations-01-image-processing-fundamentals-md",
            "title": "Image Processing Fundamentals",
            "path": "/04_Computer_Vision/01_Theory_Foundations/01_Image_Processing_Fundamentals.md",
            "isDirectory": false
          },
          {
            "id": "04-computer-vision-01-theory-foundations-02-deep-learning-for-computer-vision-md",
            "title": "Deep Learning for Computer Vision",
            "path": "/04_Computer_Vision/01_Theory_Foundations/02_Deep_Learning_for_Computer_Vision.md",
            "isDirectory": false
          },
          {
            "id": "04-computer-vision-01-theory-foundations-03-3d-computer-vision-geometry-md",
            "title": "3D Computer Vision and Geometry",
            "path": "/04_Computer_Vision/01_Theory_Foundations/03_3D_Computer_Vision_Geometry.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "04-computer-vision-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/04_Computer_Vision/02_Practical_Implementations",
        "isDirectory": true,
        "children": []
      }
    ]
  },
  {
    "id": "04-future-technologies",
    "title": "04 Future Technologies",
    "path": "/04_Future_Technologies",
    "isDirectory": true,
    "children": [
      {
        "id": "04-future-technologies-00-readme-md",
        "title": "Future Technologies",
        "path": "/04_Future_Technologies/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-01-future-ai-technologies-comprehensive-2024-2026-md",
        "title": "Future AI Technologies Comprehensive Guide 2024-2026",
        "path": "/04_Future_Technologies/01_Future_AI_Technologies_Comprehensive_2024_2026.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-02-ai-breakthrough-research-2024-2025-md",
        "title": "AI Breakthrough Research: Comprehensive Analysis 2024-2025",
        "path": "/04_Future_Technologies/02_AI_Breakthrough_Research_2024_2025.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-03-emerging-ai-trends-2025-2026-md",
        "title": "Emerging AI Trends and Predictions: 2025-2026",
        "path": "/04_Future_Technologies/03_Emerging_AI_Trends_2025_2026.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-04-industry-ai-trends-2024-2026-md",
        "title": "Industry-Specific AI Trends and Developments (2024-2026)",
        "path": "/04_Future_Technologies/04_Industry_AI_Trends_2024_2026.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "05-companies-research",
    "title": "05 Companies Research",
    "path": "/05_Companies_Research",
    "isDirectory": true,
    "children": [
      {
        "id": "05-companies-research-00-readme-md",
        "title": "Companies Research",
        "path": "/05_Companies_Research/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-01-ultimate-ai-companies-directory-md",
        "title": "Ultimate AI Companies Directory 2025",
        "path": "/05_Companies_Research/01_Ultimate_AI_Companies_Directory.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-02-ai-consulting-companies-research-md",
        "title": "AI Consulting Companies Research Report",
        "path": "/05_Companies_Research/02_AI_Consulting_Companies_Research.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-03-ai-technology-companies-research-md",
        "title": "AI Technology Companies Research Report",
        "path": "/05_Companies_Research/03_AI_Technology_Companies_Research.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-04-industry-specific-ai-companies-research-md",
        "title": "Industry-Specific AI Companies Research 2025",
        "path": "/05_Companies_Research/04_Industry_Specific_AI_Companies_Research.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-05-emerging-ai-startups-research-md",
        "title": "Emerging AI Startups Research Report 2024-2025",
        "path": "/05_Companies_Research/05_Emerging_AI_Startups_Research.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "05-generative-ai",
    "title": "05 Generative AI",
    "path": "/05_Generative_AI/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "05-generative-ai-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/05_Generative_AI/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "05-generative-ai-01-theory-foundations-01-probabilistic-generative-models-md",
            "title": "Probabilistic Generative Models: Mathematical Foundations",
            "path": "/05_Generative_AI/01_Theory_Foundations/01_Probabilistic_Generative_Models.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "05-generative-ai-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/05_Generative_AI/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "05-generative-ai-02-practical-implementations-01-transformer-based-generative-models-md",
            "title": "Transformer-Based Generative Models: Practical Implementations",
            "path": "/05_Generative_AI/02_Practical_Implementations/01_Transformer_Based_Generative_Models.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "06-ai-agents-and-autonomous",
    "title": "06 AI Agents and Autonomous",
    "path": "/06_AI_Agents_and_Autonomous/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "06-ai-agents-and-autonomous-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/06_AI_Agents_and_Autonomous/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "06-ai-agents-and-autonomous-01-theory-foundations-01-ai-agents-foundations-md",
            "title": "AI Agents and Autonomous Systems Foundations",
            "path": "/06_AI_Agents_and_Autonomous/01_Theory_Foundations/01_AI_Agents_Foundations.md",
            "isDirectory": false
          },
          {
            "id": "06-ai-agents-and-autonomous-01-theory-foundations-02-reinforcement-learning-theory-md",
            "title": "Reinforcement Learning Theory and Mathematical Foundations",
            "path": "/06_AI_Agents_and_Autonomous/01_Theory_Foundations/02_Reinforcement_Learning_Theory.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "06-ai-agents-and-autonomous-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/06_AI_Agents_and_Autonomous/02_Practical_Implementations",
        "isDirectory": true,
        "children": []
      }
    ]
  },
  {
    "id": "06-deep-learning-specialized",
    "title": "06 Deep Learning Specialized",
    "path": "/06_Deep_Learning_Specialized",
    "isDirectory": true,
    "children": [
      {
        "id": "06-deep-learning-specialized-00-readme-md",
        "title": "Deep Learning Specialized",
        "path": "/06_Deep_Learning_Specialized/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "06-deep-learning-specialized-01-deep-learning-comprehensive-guide-md",
        "title": "Comprehensive Deep Learning Terminology & Architecture Guide",
        "path": "/06_Deep_Learning_Specialized/01_Deep_Learning_Comprehensive_Guide.md",
        "isDirectory": false
      },
      {
        "id": "06-deep-learning-specialized-02-deep-learning-practical-implementations-md",
        "title": "Deep Learning Practical Implementations",
        "path": "/06_Deep_Learning_Specialized/02_Deep_Learning_Practical_Implementations.md",
        "isDirectory": false
      },
      {
        "id": "06-deep-learning-specialized-03-deep-learning-quick-reference-md",
        "title": "Deep Learning Quick Reference Guide",
        "path": "/06_Deep_Learning_Specialized/03_Deep_Learning_Quick_Reference.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "07-ai-ethics-and-safety",
    "title": "07 AI Ethics and Safety",
    "path": "/07_AI_Ethics_and_Safety/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "07-ai-ethics-and-safety-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/07_AI_Ethics_and_Safety/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "07-ai-ethics-and-safety-01-theory-foundations-01-ai-ethics-frameworks-md",
            "title": "AI Ethics Frameworks and Theoretical Foundations",
            "path": "/07_AI_Ethics_and_Safety/01_Theory_Foundations/01_AI_Ethics_Frameworks.md",
            "isDirectory": false
          },
          {
            "id": "07-ai-ethics-and-safety-01-theory-foundations-02-ai-safety-and-alignment-theory-md",
            "title": "AI Safety and Alignment Theory",
            "path": "/07_AI_Ethics_and_Safety/01_Theory_Foundations/02_AI_Safety_and_Alignment_Theory.md",
            "isDirectory": false
          },
          {
            "id": "07-ai-ethics-and-safety-01-theory-foundations-03-ai-safety-advances-2024-2025-md",
            "title": "Cutting-Edge AI Safety Developments (2024-2025)",
            "path": "/07_AI_Ethics_and_Safety/01_Theory_Foundations/03_AI_Safety_Advances_2024_2025.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "07-ai-ethics-and-safety-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/07_AI_Ethics_and_Safety/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "07-ai-ethics-and-safety-02-practical-implementations-01-ethical-ai-development-practices-md",
            "title": "Ethical AI Development Practices",
            "path": "/07_AI_Ethics_and_Safety/02_Practical_Implementations/01_Ethical_AI_Development_Practices.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "07-ai-ethics-and-safety-03-case-studies",
        "title": "03 Case Studies",
        "path": "/07_AI_Ethics_and_Safety/03_Case_Studies",
        "isDirectory": true,
        "children": [
          {
            "id": "07-ai-ethics-and-safety-03-case-studies-01-real-world-ethics-case-studies-md",
            "title": "Real-World AI Ethics Case Studies",
            "path": "/07_AI_Ethics_and_Safety/03_Case_Studies/01_Real_World_Ethics_Case_Studies.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "07-research-reports",
    "title": "07 Research Reports",
    "path": "/07_Research_Reports",
    "isDirectory": true,
    "children": [
      {
        "id": "07-research-reports-00-readme-md",
        "title": "Research Reports",
        "path": "/07_Research_Reports/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-01-advanced-ai-documentation-md",
        "title": "Advanced AI Technologies: Comprehensive Documentation",
        "path": "/07_Research_Reports/01_Advanced_AI_Documentation.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-02-ai-2024-developments-research-md",
        "title": "AI Developments and Breakthroughs: 2024 Comprehensive Research",
        "path": "/07_Research_Reports/02_AI_2024_Developments_Research.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-03-ai-consulting-detailed-analysis-md",
        "title": "AI Consulting Companies Detailed Analysis",
        "path": "/07_Research_Reports/03_AI_Consulting_Detailed_Analysis.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-04-ai-consulting-executive-summary-md",
        "title": "AI Consulting Companies Executive Summary",
        "path": "/07_Research_Reports/04_AI_Consulting_Executive_Summary.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-05-ai-consulting-quick-reference-md",
        "title": "AI Consulting Companies Quick Reference Guide",
        "path": "/07_Research_Reports/05_AI_Consulting_Quick_Reference.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "08-ai-applications-industry",
    "title": "08 AI Applications Industry",
    "path": "/08_AI_Applications_Industry/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "08-ai-applications-industry-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/08_AI_Applications_Industry/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "08-ai-applications-industry-01-theory-foundations-01-healthcare-ai-theory-md",
            "title": "Healthcare AI Theory and Foundations",
            "path": "/08_AI_Applications_Industry/01_Theory_Foundations/01_Healthcare_AI_Theory.md",
            "isDirectory": false
          },
          {
            "id": "08-ai-applications-industry-01-theory-foundations-02-advanced-llm-applications-2024-2025-md",
            "title": "Advanced LLM Applications in Healthcare (2024-2025)",
            "path": "/08_AI_Applications_Industry/01_Theory_Foundations/02_Advanced_LLM_Applications_2024_2025.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "09-emerging-interdisciplinary-ai",
    "title": "09 Emerging Interdisciplinary AI",
    "path": "/09_Emerging_Interdisciplinary_AI/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "09-emerging-interdisciplinary-ai-00-overview-md",
        "title": "IX. Emerging Interdisciplinary AI",
        "path": "/09_Emerging_Interdisciplinary_AI/00_Overview.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "10-technical-and-methodological-foundations",
    "title": "10 Technical and Methodological Foundations",
    "path": "/10_Technical_and_Methodological_Foundations/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "10-technical-and-methodological-foundations-00-overview-md",
        "title": "X. Technical and Methodological Foundations",
        "path": "/10_Technical_and_Methodological_Foundations/00_Overview.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "11-future-directions-and-advanced-concepts",
    "title": "11 Future Directions and Advanced Concepts",
    "path": "/11_Future_Directions_and_Advanced_Concepts/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "11-future-directions-and-advanced-concepts-00-overview-md",
        "title": "XI. Future Directions and Advanced Concepts",
        "path": "/11_Future_Directions_and_Advanced_Concepts/00_Overview.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "12-emerging-research-2025",
    "title": "12 Emerging Research 2025",
    "path": "/12_Emerging_Research_2025/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "12-emerging-research-2025-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/12_Emerging_Research_2025/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "12-emerging-research-2025-01-theory-foundations-01-cutting-edge-ai-research-2024-2025-md",
            "title": "Cutting-Edge AI Research Frontiers (2024-2025)",
            "path": "/12_Emerging_Research_2025/01_Theory_Foundations/01_Cutting_Edge_AI_Research_2024_2025.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "13-prompt-engineering-and-advanced-techniques",
    "title": "13 Prompt Engineering and Advanced Techniques",
    "path": "/13_Prompt_Engineering_and_Advanced_Techniques/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "13-prompt-engineering-and-advanced-techniques-00-overview-md",
        "title": "XIII. Prompt Engineering and Advanced Techniques",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/00_Overview.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-01-fundamentals-md",
        "title": "Fundamentals of Prompt Engineering",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/01_Fundamentals.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-02-chain-of-thought-reasoning-md",
        "title": "Chain-of-Thought Reasoning",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/02_Chain_of_Thought_Reasoning.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-03-advanced-techniques-md",
        "title": "Advanced Prompting Techniques (2024-2025)",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/03_Advanced_Techniques.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-04-multi-modal-agentic-md",
        "title": "Multi-modal and Agentic Prompting",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/04_Multi_modal_Agentic.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-05-advanced-prompting-techniques-md",
        "title": "Advanced Prompting Techniques",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/05_Advanced_Prompting_Techniques.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-06-optimization-strategies-md",
        "title": "Prompt Optimization Strategies",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/06_Optimization_Strategies.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-conclusion-md",
        "title": "Conclusion and Next Steps",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/CONCLUSION.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-module-summary-md",
        "title": "Module Structure and Content Summary",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/MODULE_SUMMARY.md",
        "isDirectory": false
      },
      {
        "id": "13-prompt-engineering-and-advanced-techniques-readme-md",
        "title": "Advanced Prompt Engineering and Chain-of-Thought Reasoning (2024-2025 Edition)",
        "path": "/13_Prompt_Engineering_and_Advanced_Techniques/README.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "14-ai-business-enterprise",
    "title": "14 AI Business Enterprise",
    "path": "/14_AI_Business_Enterprise/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "14-ai-business-enterprise-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/14_AI_Business_Enterprise/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "14-ai-business-enterprise-01-theory-foundations-01-enterprise-ai-strategy-and-governance-md",
            "title": "Enterprise AI Strategy and Governance",
            "path": "/14_AI_Business_Enterprise/01_Theory_Foundations/01_Enterprise_AI_Strategy_and_Governance.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "14-ai-business-enterprise-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/14_AI_Business_Enterprise/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "14-ai-business-enterprise-02-practical-implementations-01-enterprise-ai-platform-architecture-md",
            "title": "Enterprise AI Platform Architecture",
            "path": "/14_AI_Business_Enterprise/02_Practical_Implementations/01_Enterprise_AI_Platform_Architecture.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "14-ai-business-enterprise-03-case-studies",
        "title": "03 Case Studies",
        "path": "/14_AI_Business_Enterprise/03_Case_Studies",
        "isDirectory": true,
        "children": [
          {
            "id": "14-ai-business-enterprise-03-case-studies-01-enterprise-ai-transformation-case-studies-md",
            "title": "Enterprise AI Transformation Case Studies",
            "path": "/14_AI_Business_Enterprise/03_Case_Studies/01_Enterprise_AI_Transformation_Case_Studies.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "14-mlops-and-ai-deployment-strategies",
    "title": "14 MLOps and AI Deployment Strategies",
    "path": "/14_MLOps_and_AI_Deployment_Strategies/README.md",
    "isDirectory": true,
    "children": [
      {
        "id": "14-mlops-and-ai-deployment-strategies-01-mlops-fundamentals-md",
        "title": "Module 1: MLOps Fundamentals",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/01_MLOps_Fundamentals.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-02-llmops-and-generative-ai-operations-md",
        "title": "Module 2: LLMOps and Generative AI Operations",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/02_LLMops_and_Generative_AI_Operations.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-03-advanced-deployment-strategies-md",
        "title": "Module 3: Advanced Deployment Strategies",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/03_Advanced_Deployment_Strategies.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-04-infrastructure-and-orchestration-md",
        "title": "Module 4: Infrastructure and Orchestration",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/04_Infrastructure_and_Orchestration.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-05-monitoring-and-observability-md",
        "title": "Module 5: Monitoring and Observability",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/05_Monitoring_and_Observability.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-06-model-management-and-versioning-md",
        "title": "Module 6: Model Management and Versioning",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/06_Model_Management_and_Versioning.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-07-cicd-for-machine-learning-md",
        "title": "CI/CD for Machine Learning",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/07_CICD_for_Machine_Learning.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-08-edge-ai-and-federated-learning-md",
        "title": "Edge AI and Federated Learning",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/08_Edge_AI_and_Federated_Learning.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-09-aiops-and-automation-md",
        "title": "AIOps and Automation",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/09_AIOps_and_Automation.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-10-production-best-practices-md",
        "title": "Production Best Practices",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/10_Production_Best_Practices.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-11-security-and-compliance-md",
        "title": "MLOps and AI Deployment Strategies - Module 11: Security and Compliance",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/11_Security_and_Compliance.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-12-future-trends-md",
        "title": "MLOps and AI Deployment Strategies - Module 12: Future Trends and Emerging Technologies",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/12_Future_Trends.md",
        "isDirectory": false
      },
      {
        "id": "14-mlops-and-ai-deployment-strategies-readme-md",
        "title": "MLOps and AI Deployment Strategies (2024-2025 Edition)",
        "path": "/14_MLOps_and_AI_Deployment_Strategies/README.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "15-specialized-applications",
    "title": "15 Specialized Applications",
    "path": "/15_Specialized_Applications/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "15-specialized-applications-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/15_Specialized_Applications/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "15-specialized-applications-01-theory-foundations-01-healthcare-ai-theory-md",
            "title": "Healthcare AI: Theoretical Foundations",
            "path": "/15_Specialized_Applications/01_Theory_Foundations/01_Healthcare_AI_Theory.md",
            "isDirectory": false
          },
          {
            "id": "15-specialized-applications-01-theory-foundations-02-autonomous-systems-and-robotics-md",
            "title": "Autonomous Systems and Robotics: Theoretical Foundations",
            "path": "/15_Specialized_Applications/01_Theory_Foundations/02_Autonomous_Systems_and_Robotics.md",
            "isDirectory": false
          },
          {
            "id": "15-specialized-applications-01-theory-foundations-03-creative-ai-and-content-generation-md",
            "title": "Creative AI and Content Generation: Theoretical Foundations",
            "path": "/15_Specialized_Applications/01_Theory_Foundations/03_Creative_AI_and_Content_Generation.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "15-specialized-applications-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/15_Specialized_Applications/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "15-specialized-applications-02-practical-implementations-01-medical-ai-implementation-md",
            "title": "Medical AI Implementation: Practical Guide",
            "path": "/15_Specialized_Applications/02_Practical_Implementations/01_Medical_AI_Implementation.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "15-specialized-applications-03-case-studies",
        "title": "03 Case Studies",
        "path": "/15_Specialized_Applications/03_Case_Studies",
        "isDirectory": true,
        "children": [
          {
            "id": "15-specialized-applications-03-case-studies-01-healthcare-ai-breakthroughs-md",
            "title": "Healthcare AI Breakthroughs: Real-World Case Studies",
            "path": "/15_Specialized_Applications/03_Case_Studies/01_Healthcare_AI_Breakthroughs.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "16-emerging-ai-paradigms",
    "title": "16 Emerging AI Paradigms",
    "path": "/16_Emerging_AI_Paradigms/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "16-emerging-ai-paradigms-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/16_Emerging_AI_Paradigms/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "16-emerging-ai-paradigms-01-theory-foundations-01-edge-ai-and-distributed-intelligence-md",
            "title": "Edge AI and Distributed Intelligence: Theoretical Foundations",
            "path": "/16_Emerging_AI_Paradigms/01_Theory_Foundations/01_Edge_AI_and_Distributed_Intelligence.md",
            "isDirectory": false
          },
          {
            "id": "16-emerging-ai-paradigms-01-theory-foundations-02-explainable-and-interpretable-ai-md",
            "title": "Explainable and Interpretable AI: Theoretical Foundations",
            "path": "/16_Emerging_AI_Paradigms/01_Theory_Foundations/02_Explainable_and_Interpretable_AI.md",
            "isDirectory": false
          },
          {
            "id": "16-emerging-ai-paradigms-01-theory-foundations-03-ai-for-scientific-discovery-md",
            "title": "AI for Scientific Discovery: Theoretical Foundations",
            "path": "/16_Emerging_AI_Paradigms/01_Theory_Foundations/03_AI_for_Scientific_Discovery.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "16-emerging-ai-paradigms-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/16_Emerging_AI_Paradigms/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "16-emerging-ai-paradigms-02-practical-implementations-01-federated-learning-implementation-md",
            "title": "Federated Learning Implementation: Practical Guide",
            "path": "/16_Emerging_AI_Paradigms/02_Practical_Implementations/01_Federated_Learning_Implementation.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "16-emerging-ai-paradigms-03-case-studies",
        "title": "03 Case Studies",
        "path": "/16_Emerging_AI_Paradigms/03_Case_Studies",
        "isDirectory": true,
        "children": [
          {
            "id": "16-emerging-ai-paradigms-03-case-studies-01-edge-ai-success-stories-md",
            "title": "Edge AI Success Stories: Real-World Case Studies",
            "path": "/16_Emerging_AI_Paradigms/03_Case_Studies/01_Edge_AI_Success_Stories.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "17-ai-for-social-good-and-impact",
    "title": "17 AI for Social Good and Impact",
    "path": "/17_AI_for_Social_Good_and_Impact/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "17-ai-for-social-good-and-impact-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/17_AI_for_Social_Good_and_Impact/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "17-ai-for-social-good-and-impact-01-theory-foundations-01-comprehensive-overview-md",
            "title": "AI for Social Good and Impact",
            "path": "/17_AI_for_Social_Good_and_Impact/01_Theory_Foundations/01_Comprehensive_Overview.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "18-ai-policy-and-regulation",
    "title": "18 AI Policy and Regulation",
    "path": "/18_AI_Policy_and_Regulation/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "18-ai-policy-and-regulation-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/18_AI_Policy_and_Regulation/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "18-ai-policy-and-regulation-01-theory-foundations-01-comprehensive-overview-md",
            "title": "AI Policy and Regulation",
            "path": "/18_AI_Policy_and_Regulation/01_Theory_Foundations/01_Comprehensive_Overview.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "19-human-ai-collaboration-and-augmentation",
    "title": "19 Human AI Collaboration and Augmentation",
    "path": "/19_Human_AI_Collaboration_and_Augmentation/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "19-human-ai-collaboration-and-augmentation-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/19_Human_AI_Collaboration_and_Augmentation/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "19-human-ai-collaboration-and-augmentation-01-theory-foundations-01-comprehensive-overview-md",
            "title": "Human-AI Collaboration and Augmentation",
            "path": "/19_Human_AI_Collaboration_and_Augmentation/01_Theory_Foundations/01_Comprehensive_Overview.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "20-ai-entertainment-media",
    "title": "20 AI Entertainment Media",
    "path": "/20_AI_Entertainment_Media/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "20-ai-entertainment-media-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/20_AI_Entertainment_Media/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "20-ai-entertainment-media-01-theory-foundations-01-entertainment-ai-theory-md",
            "title": "Entertainment AI Theory: Foundations for AI-Generated Entertainment",
            "path": "/20_AI_Entertainment_Media/01_Theory_Foundations/01_Entertainment_AI_Theory.md",
            "isDirectory": false
          },
          {
            "id": "20-ai-entertainment-media-01-theory-foundations-02-media-and-content-ai-md",
            "title": "Media and Content AI: Theoretical Foundations",
            "path": "/20_AI_Entertainment_Media/01_Theory_Foundations/02_Media_and_Content_AI.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "20-ai-entertainment-media-02-practical-implementations",
        "title": "02 Practical Implementations",
        "path": "/20_AI_Entertainment_Media/02_Practical_Implementations",
        "isDirectory": true,
        "children": [
          {
            "id": "20-ai-entertainment-media-02-practical-implementations-01-game-ai-implementation-md",
            "title": "Game AI Implementation: Practical Guide",
            "path": "/20_AI_Entertainment_Media/02_Practical_Implementations/01_Game_AI_Implementation.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "20-ai-entertainment-media-03-case-studies",
        "title": "03 Case Studies",
        "path": "/20_AI_Entertainment_Media/03_Case_Studies",
        "isDirectory": true,
        "children": [
          {
            "id": "20-ai-entertainment-media-03-case-studies-01-ai-entertainment-innovation-md",
            "title": "AI Entertainment Innovation: Real-World Case Studies",
            "path": "/20_AI_Entertainment_Media/03_Case_Studies/01_AI_Entertainment_Innovation.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "21-ai-in-agriculture-and-food-systems",
    "title": "21 AI in Agriculture and Food Systems",
    "path": "/21_AI_in_Agriculture_and_Food_Systems/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "21-ai-in-agriculture-and-food-systems-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/21_AI_in_Agriculture_and_Food_Systems/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "21-ai-in-agriculture-and-food-systems-01-theory-foundations-01-comprehensive-overview-md",
            "title": "AI in Agriculture and Food Systems: Comprehensive Guide (2024-2025 Edition)",
            "path": "/21_AI_in_Agriculture_and_Food_Systems/01_Theory_Foundations/01_Comprehensive_Overview.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "22-ai-for-smart-cities-and-infrastructure",
    "title": "22 AI for Smart Cities and Infrastructure",
    "path": "/22_AI_for_Smart_Cities_and_Infrastructure/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-00-overview-md",
        "title": "XXII. AI for Smart Cities and Infrastructure",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/00_Overview.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-01-introduction-md",
        "title": "Introduction to AI for Smart Cities and Infrastructure",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/01_Introduction.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-02-urban-planning-and-development-md",
        "title": "Urban Planning and Development",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/02_Urban_Planning_and_Development.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-03-intelligent-transportation-systems-md",
        "title": "Intelligent Transportation Systems",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/03_Intelligent_Transportation_Systems.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-04-energy-grid-management-and-optimization-md",
        "title": "Energy Grid Management and Optimization",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/04_Energy_Grid_Management_and_Optimization.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-05-public-safety-and-security-md",
        "title": "Public Safety and Security",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/05_Public_Safety_and_Security.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-06-environmental-monitoring-and-sustainability-md",
        "title": "Environmental Monitoring and Sustainability",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/06_Environmental_Monitoring_and_Sustainability.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-07-waste-management-and-resource-optimization-md",
        "title": "Waste Management and Resource Optimization",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/07_Waste_Management_and_Resource_Optimization.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-08-citizen-services-and-engagement-md",
        "title": "Citizen Services and Engagement",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/08_Citizen_Services_and_Engagement.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-09-infrastructure-health-monitoring-md",
        "title": "Infrastructure Health Monitoring",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/09_Infrastructure_Health_Monitoring.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-10-future-trends-and-innovations-md",
        "title": "Future Trends and Innovations",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/10_Future_Trends_and_Innovations.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-11-case-studies-and-real-world-applications-md",
        "title": "Case Studies and Real-World Applications",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/11_Case_Studies_and_Real_World_Applications.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-12-implementation-guidelines-and-best-practices-md",
        "title": "Implementation Guidelines and Best Practices",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/12_Implementation_Guidelines_and_Best_Practices.md",
        "isDirectory": false
      },
      {
        "id": "22-ai-for-smart-cities-and-infrastructure-readme-md",
        "title": "AI for Smart Cities and Infrastructure: Comprehensive Guide",
        "path": "/22_AI_for_Smart_Cities_and_Infrastructure/README.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "23-ai-in-aerospace-and-defense",
    "title": "23 AI in Aerospace and Defense",
    "path": "/23_AI_in_Aerospace_and_Defense/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "23-ai-in-aerospace-and-defense-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/23_AI_in_Aerospace_and_Defense/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "23-ai-in-aerospace-and-defense-01-theory-foundations-01-comprehensive-overview-md",
            "title": "AI in Aerospace and Defense: Comprehensive Guide",
            "path": "/23_AI_in_Aerospace_and_Defense/01_Theory_Foundations/01_Comprehensive_Overview.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "24-ai-in-energy-and-climate",
    "title": "24 AI in Energy and Climate",
    "path": "/24_AI_in_Energy_and_Climate/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "24-ai-in-energy-and-climate-01-theory-foundations",
        "title": "01 Theory Foundations",
        "path": "/24_AI_in_Energy_and_Climate/01_Theory_Foundations",
        "isDirectory": true,
        "children": [
          {
            "id": "24-ai-in-energy-and-climate-01-theory-foundations-01-comprehensive-overview-md",
            "title": "24. AI in Energy and Climate",
            "path": "/24_AI_in_Energy_and_Climate/01_Theory_Foundations/01_Comprehensive_Overview.md",
            "isDirectory": false
          }
        ]
      }
    ]
  },
  {
    "id": "25-future-of-ai-and-emerging-trends",
    "title": "25 Future of AI and Emerging Trends",
    "path": "/25_Future_of_AI_and_Emerging_Trends/00_Overview.md",
    "isDirectory": true,
    "children": [
      {
        "id": "25-future-of-ai-and-emerging-trends-modules",
        "title": "modules",
        "path": "/25_Future_of_AI_and_Emerging_Trends/modules",
        "isDirectory": true,
        "children": [
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-01-introduction-md",
            "title": "Introduction to Future AI Trends",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/01_Introduction.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-02-quantum-ai-and-quantum-computing-md",
            "title": "Quantum AI and Quantum Computing",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/02_Quantum_AI_and_Quantum_Computing.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-03-neuromorphic-computing-and-brain-inspired-ai-md",
            "title": "Neuromorphic Computing and Brain-Inspired AI",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/03_Neuromorphic_Computing_and_Brain-Inspired_AI.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-04-autonomous-ai-systems-and-agi-md",
            "title": "Autonomous AI Systems and AGI",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/04_Autonomous_AI_Systems_and_AGI.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-05-ai-and-human-augmentation-md",
            "title": "AI and Human Augmentation",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/05_AI_and_Human_Augmentation.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-06-edge-ai-and-distributed-intelligence-md",
            "title": "Edge AI and Distributed Intelligence",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/06_Edge_AI_and_Distributed_Intelligence.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-07-ai-ethics-and-governance-evolution-md",
            "title": "AI Ethics and Governance Evolution",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/07_AI_Ethics_and_Governance_Evolution.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-08-sustainable-and-green-ai-md",
            "title": "Sustainable and Green AI",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/08_Sustainable_and_Green_AI.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-09-ai-in-space-exploration-and-beyond-md",
            "title": "AI in Space Exploration and Beyond",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/09_AI_in_Space_Exploration_and_Beyond.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-10-societal-and-economic-impacts-md",
            "title": "Societal and Economic Impacts",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/10_Societal_and_Economic_Impacts.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-11-emerging-research-frontiers-md",
            "title": "Emerging Research Frontiers",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/11_Emerging_Research_Frontiers.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-12-future-scenarios-md",
            "title": "Future Scenarios",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/12_Future_Scenarios.md",
            "isDirectory": false
          },
          {
            "id": "25-future-of-ai-and-emerging-trends-modules-13-preparation-and-adaptation-md",
            "title": "Preparation and Adaptation",
            "path": "/25_Future_of_AI_and_Emerging_Trends/modules/13_Preparation_and_Adaptation.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "25-future-of-ai-and-emerging-trends-summary-md",
        "title": "Future of AI and Emerging Trends - Summary",
        "path": "/25_Future_of_AI_and_Emerging_Trends/SUMMARY.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "13-prompt-engineering-and-advanced-techniques-md",
    "title": "Advanced Prompt Engineering and Chain-of-Thought Reasoning (2024-2025 Edition)",
    "path": "/13_Prompt_Engineering_and_Advanced_Techniques.md",
    "isDirectory": false
  },
  {
    "id": "14-mlops-and-ai-deployment-strategies-md",
    "title": "MLOps and AI Deployment Strategies (2024-2025 Edition)",
    "path": "/14_MLOps_and_AI_Deployment_Strategies.md",
    "isDirectory": false
  },
  {
    "id": "15-state-space-models-and-mamba-architecture-md",
    "title": "State Space Models and Mamba Architecture (2024-2025 Edition)",
    "path": "/15_State_Space_Models_and_Mamba_Architecture.md",
    "isDirectory": false
  },
  {
    "id": "16-advanced-multimodal-ai-integration-md",
    "title": "Advanced Multimodal AI Integration (2024-2025 Edition)",
    "path": "/16_Advanced_Multimodal_AI_Integration.md",
    "isDirectory": false
  },
  {
    "id": "knowledge-system-readme-md",
    "title": "Advanced Intelligent Cross-Referencing and Knowledge Graph System",
    "path": "/KNOWLEDGE_SYSTEM_README.md",
    "isDirectory": false
  }
];

export const additionalDocs = [
  {
    "id": "00-structure-guide-md",
    "title": "AI Documentation System Structure Guide",
    "path": "/00_STRUCTURE_GUIDE.md",
    "isDirectory": false
  },
  {
    "id": "20-ai-in-entertainment-and-media-md",
    "title": "AI in Entertainment and Media: Comprehensive Guide (2024-2025 Edition)",
    "path": "/20_AI_in_Entertainment_and_Media.md",
    "isDirectory": false
  },
  {
    "id": "22-ai-for-smart-cities-and-infrastructure-md",
    "title": "AI for Smart Cities and Infrastructure: Comprehensive Guide",
    "path": "/22_AI_for_Smart_Cities_and_Infrastructure.md",
    "isDirectory": false
  },
  {
    "id": "25-future-of-ai-and-emerging-trends-md",
    "title": "25. Future of AI and Emerging Trends",
    "path": "/25_Future_of_AI_and_Emerging_Trends.md",
    "isDirectory": false
  },
  {
    "id": "ai-documentation-cross-reference-summary-md",
    "title": "AI Documentation Cross-Reference System - Implementation Summary",
    "path": "/AI_DOCUMENTATION_CROSS_REFERENCE_SUMMARY.md",
    "isDirectory": false
  },
  {
    "id": "ai-documentation-update-summary-2024-2025-md",
    "title": "AI Documentation Update Summary: 2024-2025 Cutting-Edge Developments",
    "path": "/AI_Documentation_Update_Summary_2024_2025.md",
    "isDirectory": false
  },
  {
    "id": "ai-research-report-2024-2025-md",
    "title": "AI Research Report: Latest Developments and Trends (2024-2025)",
    "path": "/AI_Research_Report_2024_2025.md",
    "isDirectory": false
  },
  {
    "id": "code-of-conduct-md",
    "title": "Contributor Covenant Code of Conduct",
    "path": "/CODE_OF_CONDUCT.md",
    "isDirectory": false
  },
  {
    "id": "collaboration-system-readme-md",
    "title": "Real-Time Collaboration System for AI Documentation",
    "path": "/COLLABORATION_SYSTEM_README.md",
    "isDirectory": false
  },
  {
    "id": "contributing-md",
    "title": "Contributing to the Comprehensive AI Documentation System",
    "path": "/CONTRIBUTING.md",
    "isDirectory": false
  },
  {
    "id": "cross-reference-readme-md",
    "title": "AI Documentation Cross-Reference System",
    "path": "/CROSS_REFERENCE_README.md",
    "isDirectory": false
  },
  {
    "id": "cross-reference-system-md",
    "title": "AI Documentation Cross-Reference System",
    "path": "/cross_reference_system.md",
    "isDirectory": false
  },
  {
    "id": "example-projects-master-md",
    "title": "Comprehensive AI Example Projects",
    "path": "/EXAMPLE_PROJECTS_MASTER.md",
    "isDirectory": false
  },
  {
    "id": "navigation-index-md",
    "title": "AI Documentation - Master Navigation Index",
    "path": "/NAVIGATION_INDEX.md",
    "isDirectory": false
  }
];

export const examplesSections = [
  {
    "id": "01-main-guides",
    "title": "01 Main Guides",
    "path": "/01_Main_Guides",
    "isDirectory": true,
    "children": [
      {
        "id": "01-main-guides-01-ai-comprehensive-guide",
        "title": "01 AI Comprehensive Guide",
        "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/README.md",
        "isDirectory": true,
        "children": [
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-01-introduction-to-ai-md",
            "title": "Chapter 1: Introduction to Artificial Intelligence",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/01_Introduction_to_AI.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-02-philosophical-origins-md",
            "title": "Chapter 2: The Philosophical Origins",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/02_Philosophical_Origins.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-03-birth-of-ai-md",
            "title": "Chapter 3: The Birth of AI (1940s-1950s)",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/03_Birth_of_AI.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-04-early-ai-approaches-md",
            "title": "Chapter 4: Early AI Approaches (1950s-1970s)",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/04_Early_AI_Approaches.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-05-mathematical-foundations-md",
            "title": "Chapter 5: Mathematical Foundations",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/05_Mathematical_Foundations.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-06-computational-theory-md",
            "title": "Chapter 6: Computational Theory",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/06_Computational_Theory.md",
            "isDirectory": false
          },
          {
            "id": "01-main-guides-01-ai-comprehensive-guide-readme-md",
            "title": "The Ultimate Guide to Artificial Intelligence: From Scratch to Latest Technologies",
            "path": "/01_Main_Guides/01_AI_Comprehensive_Guide/README.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "01-main-guides-00-readme-md",
        "title": "Main Guides",
        "path": "/01_Main_Guides/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "01-main-guides-01-ai-comprehensive-guide-md",
        "title": "The Ultimate Guide to Artificial Intelligence: From Scratch to Latest Technologies",
        "path": "/01_Main_Guides/01_AI_Comprehensive_Guide.md",
        "isDirectory": false
      },
      {
        "id": "01-main-guides-02-ai-comprehensive-guide-plan-md",
        "title": "AI Comprehensive Guide: From Scratch to Latest Technologies",
        "path": "/01_Main_Guides/02_AI_Comprehensive_Guide_Plan.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "02-industry-examples",
    "title": "02 Industry Examples",
    "path": "/02_Industry_Examples",
    "isDirectory": true,
    "children": [
      {
        "id": "02-industry-examples-02-healthcare-ai-examples",
        "title": "02 Healthcare AI Examples",
        "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/README.md",
        "isDirectory": true,
        "children": [
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-00-healthcare-ai-examples-index-md",
            "title": "Healthcare AI Examples: Modular Documentation",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/00_Healthcare_AI_Examples_Index.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-01-medical-imaging-and-diagnostics-md",
            "title": "Medical Imaging and Diagnostics AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/01_Medical_Imaging_and_Diagnostics.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-02-electronic-health-records-md",
            "title": "Electronic Health Records (EHR) Management AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/02_Electronic_Health_Records.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-03-drug-discovery-and-development-md",
            "title": "Drug Discovery and Development AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/03_Drug_Discovery_and_Development.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-04-clinical-decision-support-md",
            "title": "Clinical Decision Support Systems AI",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/04_Clinical_Decision_Support.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-05-implementation-and-integration-md",
            "title": "Implementation and Integration Strategies",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/05_Implementation_and_Integration.md",
            "isDirectory": false
          },
          {
            "id": "02-industry-examples-02-healthcare-ai-examples-readme-md",
            "title": "Healthcare AI Examples - Modular Documentation",
            "path": "/02_Industry_Examples/02_Healthcare_AI_Examples/README.md",
            "isDirectory": false
          }
        ]
      },
      {
        "id": "02-industry-examples-00-industry-examples-index-md",
        "title": "AI Examples Master Index",
        "path": "/02_Industry_Examples/00_Industry_Examples_Index.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-00-readme-md",
        "title": "Industry Examples",
        "path": "/02_Industry_Examples/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-01-finance-ai-examples-md",
        "title": "AI in Finance: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/01_Finance_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-02-healthcare-ai-examples-md",
        "title": "AI Examples in Healthcare: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/02_Healthcare_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-03-manufacturing-ai-examples-md",
        "title": "AI Examples in Manufacturing: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/03_Manufacturing_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-04-ecommerce-ai-examples-md",
        "title": "AI Examples in E-commerce: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/04_Ecommerce_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-05-agriculture-ai-examples-md",
        "title": "AI Examples in Agriculture: Comprehensive Implementation Guide",
        "path": "/02_Industry_Examples/05_Agriculture_AI_Examples.md",
        "isDirectory": false
      },
      {
        "id": "02-industry-examples-06-education-ai-examples-md",
        "title": "AI in Education: Comprehensive Implementation Examples",
        "path": "/02_Industry_Examples/06_Education_AI_Examples.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "03-terminology-references",
    "title": "03 Terminology References",
    "path": "/03_Terminology_References",
    "isDirectory": true,
    "children": [
      {
        "id": "03-terminology-references-00-readme-md",
        "title": "Terminology References",
        "path": "/03_Terminology_References/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "03-terminology-references-01-ai-comprehensive-terminology-md",
        "title": "AI/ML/DL Comprehensive Terminology Master Reference",
        "path": "/03_Terminology_References/01_AI_Comprehensive_Terminology.md",
        "isDirectory": false
      },
      {
        "id": "03-terminology-references-02-ml-dl-comprehensive-terminology-md",
        "title": "Comprehensive AI/ML/DL Terminology Guide",
        "path": "/03_Terminology_References/02_ML_DL_Comprehensive_Terminology.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "04-future-technologies",
    "title": "04 Future Technologies",
    "path": "/04_Future_Technologies",
    "isDirectory": true,
    "children": [
      {
        "id": "04-future-technologies-00-readme-md",
        "title": "Future Technologies",
        "path": "/04_Future_Technologies/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-01-future-ai-technologies-comprehensive-2024-2026-md",
        "title": "Future AI Technologies Comprehensive Guide 2024-2026",
        "path": "/04_Future_Technologies/01_Future_AI_Technologies_Comprehensive_2024_2026.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-02-ai-breakthrough-research-2024-2025-md",
        "title": "AI Breakthrough Research: Comprehensive Analysis 2024-2025",
        "path": "/04_Future_Technologies/02_AI_Breakthrough_Research_2024_2025.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-03-emerging-ai-trends-2025-2026-md",
        "title": "Emerging AI Trends and Predictions: 2025-2026",
        "path": "/04_Future_Technologies/03_Emerging_AI_Trends_2025_2026.md",
        "isDirectory": false
      },
      {
        "id": "04-future-technologies-04-industry-ai-trends-2024-2026-md",
        "title": "Industry-Specific AI Trends and Developments (2024-2026)",
        "path": "/04_Future_Technologies/04_Industry_AI_Trends_2024_2026.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "05-companies-research",
    "title": "05 Companies Research",
    "path": "/05_Companies_Research",
    "isDirectory": true,
    "children": [
      {
        "id": "05-companies-research-00-readme-md",
        "title": "Companies Research",
        "path": "/05_Companies_Research/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-01-ultimate-ai-companies-directory-md",
        "title": "Ultimate AI Companies Directory 2025",
        "path": "/05_Companies_Research/01_Ultimate_AI_Companies_Directory.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-02-ai-consulting-companies-research-md",
        "title": "AI Consulting Companies Research Report",
        "path": "/05_Companies_Research/02_AI_Consulting_Companies_Research.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-03-ai-technology-companies-research-md",
        "title": "AI Technology Companies Research Report",
        "path": "/05_Companies_Research/03_AI_Technology_Companies_Research.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-04-industry-specific-ai-companies-research-md",
        "title": "Industry-Specific AI Companies Research 2025",
        "path": "/05_Companies_Research/04_Industry_Specific_AI_Companies_Research.md",
        "isDirectory": false
      },
      {
        "id": "05-companies-research-05-emerging-ai-startups-research-md",
        "title": "Emerging AI Startups Research Report 2024-2025",
        "path": "/05_Companies_Research/05_Emerging_AI_Startups_Research.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "06-deep-learning-specialized",
    "title": "06 Deep Learning Specialized",
    "path": "/06_Deep_Learning_Specialized",
    "isDirectory": true,
    "children": [
      {
        "id": "06-deep-learning-specialized-00-readme-md",
        "title": "Deep Learning Specialized",
        "path": "/06_Deep_Learning_Specialized/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "06-deep-learning-specialized-01-deep-learning-comprehensive-guide-md",
        "title": "Comprehensive Deep Learning Terminology & Architecture Guide",
        "path": "/06_Deep_Learning_Specialized/01_Deep_Learning_Comprehensive_Guide.md",
        "isDirectory": false
      },
      {
        "id": "06-deep-learning-specialized-02-deep-learning-practical-implementations-md",
        "title": "Deep Learning Practical Implementations",
        "path": "/06_Deep_Learning_Specialized/02_Deep_Learning_Practical_Implementations.md",
        "isDirectory": false
      },
      {
        "id": "06-deep-learning-specialized-03-deep-learning-quick-reference-md",
        "title": "Deep Learning Quick Reference Guide",
        "path": "/06_Deep_Learning_Specialized/03_Deep_Learning_Quick_Reference.md",
        "isDirectory": false
      }
    ]
  },
  {
    "id": "07-research-reports",
    "title": "07 Research Reports",
    "path": "/07_Research_Reports",
    "isDirectory": true,
    "children": [
      {
        "id": "07-research-reports-00-readme-md",
        "title": "Research Reports",
        "path": "/07_Research_Reports/00_Readme.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-01-advanced-ai-documentation-md",
        "title": "Advanced AI Technologies: Comprehensive Documentation",
        "path": "/07_Research_Reports/01_Advanced_AI_Documentation.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-02-ai-2024-developments-research-md",
        "title": "AI Developments and Breakthroughs: 2024 Comprehensive Research",
        "path": "/07_Research_Reports/02_AI_2024_Developments_Research.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-03-ai-consulting-detailed-analysis-md",
        "title": "AI Consulting Companies Detailed Analysis",
        "path": "/07_Research_Reports/03_AI_Consulting_Detailed_Analysis.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-04-ai-consulting-executive-summary-md",
        "title": "AI Consulting Companies Executive Summary",
        "path": "/07_Research_Reports/04_AI_Consulting_Executive_Summary.md",
        "isDirectory": false
      },
      {
        "id": "07-research-reports-05-ai-consulting-quick-reference-md",
        "title": "AI Consulting Companies Quick Reference Guide",
        "path": "/07_Research_Reports/05_AI_Consulting_Quick_Reference.md",
        "isDirectory": false
      }
    ]
  }
];

// Helper function to flatten the tree for search
export function flattenDocs(docs) {
  const result = [];

  function flatten(items, parentPath = '') {
    for (const item of items) {
      result.push({
        id: item.id,
        title: item.title,
        path: item.path,
        parentPath: parentPath
      });

      if (item.children && item.children.length > 0) {
        flatten(item.children, item.title);
      }
    }
  }

  flatten(docs);
  return result;
}

// Get all documents for search
export function getAllDocs() {
  return [
    ...flattenDocs(docsStructure),
    ...flattenDocs(examplesSections),
    ...additionalDocs.map(d => ({ ...d, parentPath: 'Root' }))
  ];
}
